const fs = require('fs'), vm = require('vm'), assert = require('assert');
const elements = {};
const el = id => elements[id] ??= ({ textContent: '', hidden: false, disabled: false, style: {}, addEventListener() {}, getContext() { return new Proxy({}, { get: () => () => {} }); } });
const sandbox = { assert, document: { getElementById: el, querySelectorAll: () => [], addEventListener() {} }, localStorage: { getItem: () => null, setItem() {} }, setInterval: () => 1, clearInterval() {} };
vm.createContext(sandbox); vm.runInContext(fs.readFileSync('game.js', 'utf8'), sandbox);
vm.runInContext(`
start(); assert(item.type === 0 && elapsed === 0 && applesEaten === 0);
for(let i=0;i<5;i++) tick(); assert(score === 1 && applesEaten === 1 && snake.length === 4, 'regular apple');
food={x:14,y:10}; tick(); assert(combo === 2 && score === 3 && applesEaten === 2, 'combo bonus');
goldApple={x:15,y:10,expires:9000,movesAt:9000}; tick(); assert(score === 10 && applesEaten === 3 && snake.length === 6, 'gold apple and combo');
elapsed=lastAppleAt+COMBO_MS; tick(); assert(combo === 0, 'combo timeout');
start(); elapsed=6900; nextGoldAt=7000; tick(); assert(goldApple && goldApple.expires > elapsed, 'gold spawn');
const oldGold=goldApple; elapsed=goldApple.movesAt-stepMs; tick(); assert(goldApple && (goldApple.x!==oldGold.x || goldApple.y!==oldGold.y), 'gold moves');
start(); item={x:9,y:10,type:0,expires:12000}; tick(); assert(score===3 && snake.length===3,'cherry');
item={x:10,y:10,type:1,expires:12000}; tick(); assert(slowMs===8000 && stepMs===300,'snow');
pause(); const remaining=slowMs,time=elapsed; tick(); assert(slowMs===remaining && elapsed===time,'pause freezes timers'); pause();
item={x:11,y:10,type:2,expires:12000}; tick(); assert(shield,'shield');
snake=[{x:19,y:10},{x:18,y:10},{x:17,y:10}]; dir=directions.right; queue=[]; tick(); assert(state==='paused'&&!shield,'shield rescue');
turn('up'); pause(); tick(); assert(state==='playing'&&snake[0].y===9,'safe escape');
start(); elapsed=level.timeMs-stepMs; tick(); assert(state==='over' && $('title').textContent==='时间到啦！','time failure');
start(); applesEaten=7; food={x:9,y:10}; tick(); assert(state==='over' && $('title').textContent==='第一关完成！' && nextLevel===2,'level one win');
start(nextLevel); assert(currentLevel===2 && obstacles.length===8 && portals.length===2 && level.target===12,'level two setup');
snake=[{x:1,y:10},{x:0,y:10}]; dir=directions.right; queue=[]; food={x:13,y:10}; tick(); assert(snake[0].x===17 && snake[0].y===10,'portal travel');
start(2); snake=[{x:3,y:4},{x:2,y:4}]; dir=directions.right; queue=[]; tick(); assert(state==='over','rock collision');
start(2); shield=true; snake=[{x:3,y:4},{x:2,y:4}]; dir=directions.right; queue=[]; tick(); assert(state==='paused'&&!shield,'shield blocks rock');
start(2); applesEaten=11; food={x:9,y:10}; tick(); assert(state==='over' && $('title').textContent==='石头迷宫完成！','level two win');
start(); assert(!shield && slowMs===0 && score===0 && applesEaten===0 && stepMs===180,'restart resets');
`, sandbox);
console.log('PASS: levels, apples, combo, gold apple, items, pause, shield, portal, rocks and restart');
